[package]
name = "autograph"
version = "0.1.0"
edition = "2024"

[lib]
name = "autograph"
crate-type = ["cdylib"]

[dependencies]
autograph_core = { path = "autograph_core" }

[dependencies.pyo3]
version = "0.24.0"
features = ["abi3-py38"]