[package]
name = "autograph_core"
version = "0.1.0"
edition = "2024"

[dependencies]
dot-parser = "0.6.0"
rand = "0.9.2"
rand_distr = "0.5.1"
rayon = "1.11.0"
serde = "1.0.228"
serde_json = "1.0.145"

[dev-dependencies]
tempfile = "3.22.0"
